import { ApiClient } from './apiClient';

/**
 * Service to handle Administration System Settings.
 */
export class AdminService {
  private client: ApiClient;

  constructor(client: ApiClient) {
    this.client = client;
  }

 /**
   * Fetches the current client configuration
   */
  async getClientConfig(clientId: number = 54) {
    const endpoint = `/OacWeb/oac/system/GetClientConfigById?clientId=${clientId}&previousClientId=0`;
    const response = await this.client.get(endpoint);
    return await response.json();
  }

  /**
   * Updates a specific setting by fetching the current state first.
   * Use this to change settings one-at-a-time.
   * @param settingsToUpdate - Object containing the keys and new values (e.g. { SmsEnabled: true })
   */
  async updateConfigSetting(settingsToUpdate: Record<string, any>) {
    const endpoint = '/OacWeb/oac/system/SaveAdministrationSystemSettings';
    
    // 1. Get the current state so we don't overwrite other settings with stale hardcoded data
    const currentConfig = await this.getClientConfig();

    // 2. Prepare the originalValuesMap for Breeze.js tracking
    const originalValuesMap: Record<string, any> = {};
    for (const key in settingsToUpdate) {
      originalValuesMap[key] = currentConfig[key]; // Store what it WAS
    }

    // 3. Merge the new changes into the configuration
    const updatedConfig = { 
      ...currentConfig, 
      ...settingsToUpdate,
      ChangedDate: new Date().toISOString() 
    };

    // 4. Wrap in the required Entity structure
    const payload = {
      entities: [
        {
          ...updatedConfig,
          entityAspect: {
            entityTypeName: "ClientConfiguration:#Oac.Model.Data.SystemData",
            defaultResourceName: "ClientConfigurations",
            entityState: "Modified",
            originalValuesMap: originalValuesMap,
            autoGeneratedKey: {
              propertyName: "ClientConfigurationId",
              autoGeneratedKeyType: "Identity"
            }
          }
        }
      ],
      saveOptions: { tag: "54;140823;false;[];null" }
    };

    return await this.client.post(endpoint, payload);
  }

  /**
   * Adds a new holiday or updates an existing one.
   * Path: /OacWeb/oac/client/SaveHoliday
   * @param holidayData - The holiday entity object (e.g., HolidayId, HolidayName, Date, etc.)
   * @param saveOptions - The save options containing the tag (e.g., { tag: "54,1" })
   * @returns Promise resolving to the API response.
   */
  async saveHoliday(holidayData: any, saveOptions: any) {
    const endpoint = '/OacWeb/oac/client/SaveHoliday';

    const requestBody = {
      entities: [holidayData],
      saveOptions: saveOptions,
    };

    // The ApiClient automatically handles the full URL and authentication
    return await this.client.post(endpoint, requestBody);
  }

/**
   * Fetches all holidays based on year and location.
   * Path: /OacWeb/oac/client/AllHolidays
   * @param year - The year to filter holidays (e.g., 2026)
   * @param clientId - The unique identifier for the client
   * @param currentLocationId - The current location ID
   * @returns Promise resolving to the API response.
   */
  async getAllHolidays(year: number | string, clientId: string | number, currentLocationId: string | number) {
    const endpoint = '/OacWeb/oac/client/AllHolidays';

    // Constructing query parameters based on the curl request
    const params = {
      '$filter': `year(Date) eq ${year}`,
      '$orderby': 'Location/FkLocationTypeId',
      '$expand': 'Location',
      'clientId': clientId.toString(),
      'currentLocationId': currentLocationId.toString(),
    };

    // ApiClient handles the baseURL, auth headers, and logging
    return await this.client.get(endpoint, params);
  }

  /**
 * Deletes a holiday by sending the entity with a 'Deleted' state.
 * Path: /OacWeb/oac/client/DeleteHoliday
 * @param holidayData - The full holiday object retrieved from the GET call
 * @param clientId - The client ID for the saveOptions tag
 */
async deleteHoliday(holidayData: any, clientId: string | number) {
  const endpoint = '/OacWeb/oac/client/DeleteHoliday';

  const requestBody = {
  entities: [
    {
      ...holidayData, // Spread the existing holiday properties
      entityAspect: {
        entityTypeName: "Holiday:#Oac.Model.Data.ClientData",
        defaultResourceName: "Holidays",
        entityState: "Deleted", // CRITICAL: This tells the server to delete it
        originalValuesMap: {
            // Some APIs require the original Start/End times to verify concurrency
            StartTime: holidayData.StartTime,
            EndTime: holidayData.EndTime
        }
      }
    }
  ],
  saveOptions: { 
    tag: Number(clientId) // Ensure this is a number, not a string
  }
};
  console.log("------------------------------ ");
  console.log("requestBody : ",requestBody);

  return await this.client.post(endpoint, requestBody);
}
}