import { ApiClient } from './apiClient';
import { DateUtils } from '../utils/dateUtils';

/**
 * Service to handle appointment operations including retrieval and deletion.
 */
export class AppointmentService {
  private client: ApiClient;

  constructor(client: ApiClient) {
    this.client = client;
  }

  /**
   * Fetches all appointments within a specified date range.
   * @param clientId - The client ID
   * @param currentLocation - Current location filter
   * @param firstDate - Start date in "M/D/YYYY, H:mm:ss AM/PM" format
   * @param lastDate - End date in "M/D/YYYY, H:mm:ss AM/PM" format
   * @param selectedLocation - Location filter (-1 for all)
   * @returns Promise resolving to the API response with appointments
   */
  async getAllAppointments(
    clientId: number = 54,
    currentLocation: number = 1,
    firstDate: string,
    lastDate: string,
    selectedLocation: number = -1
  ) {
    const endpoint = '/OacWeb/oac/client/ActionCenterAppointments';
    
    const params = {
      clientId: clientId.toString(),
      currentLocation: currentLocation.toString(),
      firstDate: firstDate,
      lastDate: lastDate,
      changeAssignedUser: '-1',
      selectedLocation: selectedLocation.toString(),
      getTimesInLoggedInUserTimeZone: 'true'
    };

    return await this.client.get(endpoint, params);
  }

  /**
   * Fetches detailed appointment data by appointment IDs.
   * @param appointmentIds - Array of appointment IDs
   * @param clientId - The client ID
   * @returns Promise resolving to the API response with detailed appointment data
   */
  async getAppointmentsByIds(appointmentIds: number[], clientId: number = 54) {
    const endpoint = '/OacWeb/oac/client/GetAppointmentsById';
    
    // Build query parameters for appointment IDs
    const params: Record<string, string> = {
      ClientID: clientId.toString()
    };
    
    appointmentIds.forEach((id, index) => {
      params[`AppointmentIds[${index}]`] = id.toString();
    });

    return await this.client.get(endpoint, params);
  }

  /**
   * Bulk deletes appointments by setting ActiveStatus to 0.
   * @param appointments - Array of appointment objects to delete
   * @returns Promise resolving to the API response
   */
  async bulkDeleteAppointments(appointments: any[]) {
    const endpoint = '/OacWeb/oac/client/BulkDeleteAppointments';
    
    // Limit to first 3 appointments for testing
    // const appointmentsToDelete = appointments.slice(0, 3);
    const appointmentsToDelete = appointments;
    
    // Prepare entities for deletion - set ActiveStatus to 0 and entityState to Modified
    const entities = appointmentsToDelete.map(appointment => ({
      ...appointment,
      ActiveStatus: 0, // Set to inactive for deletion
      entityAspect: {
        entityTypeName: "Appointment:#Oac.Model.Data.ClientData",
        defaultResourceName: "Appointments",
        entityState: "Modified",
        originalValuesMap: {
          ActiveStatus: 1 // Original status was active
        },
        autoGeneratedKey: {
          propertyName: "AppointmentId",
          autoGeneratedKeyType: "Identity"
        }
      }
    }));

    const requestBody = {
      entities: entities,
      saveOptions: {
        tag: {
          clientId: 54,
          ApptsToDelete: []
        }
      }
    };

    return await this.client.post(endpoint, requestBody);
  }

  /**
   * Formats date for API calls in the required format.
   * @param date - Date object to format
   * @param timeString - Time string in "H:mm:ss AM/PM" format
   * @returns Formatted date string for API
   */
  private formatDateForAPI(date: Date, timeString: string): string {
    const month = (date.getMonth() + 1).toString();
    const day = date.getDate().toString();
    const year = date.getFullYear().toString();
    return `${month}/${day}/${year}, ${timeString}`;
  }

  /**
   * Gets date range for appointment queries (today to 4 business days).
   * @returns Object with firstDate and lastDate formatted for API
   */
  getDateRangeForQuery() {
    const today = DateUtils.getToday();
    const endDate = DateUtils.addBusinessDays(today, 4);
    
    const firstDate = this.formatDateForAPI(today, '12:00:00 AM');
    const lastDate = this.formatDateForAPI(endDate, '11:59:59 PM');
    
    return { firstDate, lastDate };
  }

  /**
   * Filters appointments by location codes.
   * @param appointments - Array of appointments to filter
   * @param locationCodes - Array of location codes to include
   * @returns Filtered appointments grouped by location code
   */
  filterAppointmentsByLocation(appointments: any[], locationCodes: string[]) {
    const filtered: Record<string, any[]> = {};
    
    // Initialize filtered object with location codes
    locationCodes.forEach(code => {
      filtered[code] = [];
    });
    
    // Filter appointments by LocationCode
    appointments.forEach(appointment => {
      const locationCode = appointment.LocationCode;
      if (locationCode && locationCodes.includes(locationCode)) {
        const targetArray = filtered[locationCode];
        if (targetArray) {
          targetArray.push(appointment);
        }
      }
    });
    
    return filtered;
  }
}
